name: 'test action'
description: 'testing the actions '

runs:
  using: "composite"
  steps:
  
    - name: Pr message test 
      id: pr_test
      #if: ${{ failure() && steps.pr_test.conclusion == 'failure' }}
      env:
       PR_NUMBER: "${{ github.event.number }}"
       GITHUB_TOKEN: ${{ github.token }}
      run: |        
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $GITHUB_TOKEN " \
          https://api.github.com/repos/$OWNER/$REPO/issues/$PR_NUMBER/comments \
          -d '{"body":"**Testing** 123"}'
      shell: bash
   
   