name: 'test action'
description: 'testing the actions '

runs:
  using: "composite"
  steps:
  
    - name: Pr message test 
      id: pr_test
      #if: ${{ failure() && steps.pr_test.conclusion == 'failure' }}
      # if: ${{ success() }}
      env:
       PR_URL: "${{ github.event.pull_request.url }}"
      run: |        
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token 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" \
          https://api.github.com/repos/Dayanandachari/Github_action_repo/issues/5/comments \
          -d '{"body":"**PR Message Testing ** "}'
      shell: bash
   
   